/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeisekarteRouteImport } from './routes/speisekarte'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffTeamRouteImport } from './routes/staff.team'
import { Route as StaffSitzbereicheRouteImport } from './routes/staff.sitzbereiche'
import { Route as StaffSettingsRouteImport } from './routes/staff.settings'
import { Route as StaffReservierungenRouteImport } from './routes/staff.reservierungen'
import { Route as StaffOeffnungszeitenRouteImport } from './routes/staff.oeffnungszeiten'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as StaffEventsRouteImport } from './routes/staff.events'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as StaffAnalyticsRouteImport } from './routes/staff.analytics'
import { Route as StaffReservierungenIndexRouteImport } from './routes/staff.reservierungen.index'
import { Route as StaffEventsIndexRouteImport } from './routes/staff.events.index'
import { Route as StaffReservierungenIdRouteImport } from './routes/staff.reservierungen.$id'
import { Route as StaffEventsNewRouteImport } from './routes/staff.events.new'
import { Route as StaffEventsIdRouteImport } from './routes/staff.events.$id'

const SpeisekarteRoute = SpeisekarteRouteImport.update({
  id: '/speisekarte',
  path: '/speisekarte',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffTeamRoute = StaffTeamRouteImport.update({
  id: '/staff/team',
  path: '/staff/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSitzbereicheRoute = StaffSitzbereicheRouteImport.update({
  id: '/staff/sitzbereiche',
  path: '/staff/sitzbereiche',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/staff/settings',
  path: '/staff/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReservierungenRoute = StaffReservierungenRouteImport.update({
  id: '/staff/reservierungen',
  path: '/staff/reservierungen',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOeffnungszeitenRoute = StaffOeffnungszeitenRouteImport.update({
  id: '/staff/oeffnungszeiten',
  path: '/staff/oeffnungszeiten',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffEventsRoute = StaffEventsRouteImport.update({
  id: '/staff/events',
  path: '/staff/events',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAnalyticsRoute = StaffAnalyticsRouteImport.update({
  id: '/staff/analytics',
  path: '/staff/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReservierungenIndexRoute =
  StaffReservierungenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffReservierungenRoute,
  } as any)
const StaffEventsIndexRoute = StaffEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffEventsRoute,
} as any)
const StaffReservierungenIdRoute = StaffReservierungenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffReservierungenRoute,
} as any)
const StaffEventsNewRoute = StaffEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StaffEventsRoute,
} as any)
const StaffEventsIdRoute = StaffEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/reservation': typeof ReservationRoute
  '/restaurant': typeof RestaurantRoute
  '/speisekarte': typeof SpeisekarteRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/events': typeof StaffEventsRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/staff/oeffnungszeiten': typeof StaffOeffnungszeitenRoute
  '/staff/reservierungen': typeof StaffReservierungenRouteWithChildren
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/sitzbereiche': typeof StaffSitzbereicheRoute
  '/staff/team': typeof StaffTeamRoute
  '/staff/events/$id': typeof StaffEventsIdRoute
  '/staff/events/new': typeof StaffEventsNewRoute
  '/staff/reservierungen/$id': typeof StaffReservierungenIdRoute
  '/staff/events/': typeof StaffEventsIndexRoute
  '/staff/reservierungen/': typeof StaffReservierungenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/reservation': typeof ReservationRoute
  '/restaurant': typeof RestaurantRoute
  '/speisekarte': typeof SpeisekarteRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/oeffnungszeiten': typeof StaffOeffnungszeitenRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/sitzbereiche': typeof StaffSitzbereicheRoute
  '/staff/team': typeof StaffTeamRoute
  '/staff/events/$id': typeof StaffEventsIdRoute
  '/staff/events/new': typeof StaffEventsNewRoute
  '/staff/reservierungen/$id': typeof StaffReservierungenIdRoute
  '/staff/events': typeof StaffEventsIndexRoute
  '/staff/reservierungen': typeof StaffReservierungenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/reservation': typeof ReservationRoute
  '/restaurant': typeof RestaurantRoute
  '/speisekarte': typeof SpeisekarteRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/events': typeof StaffEventsRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/staff/oeffnungszeiten': typeof StaffOeffnungszeitenRoute
  '/staff/reservierungen': typeof StaffReservierungenRouteWithChildren
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/sitzbereiche': typeof StaffSitzbereicheRoute
  '/staff/team': typeof StaffTeamRoute
  '/staff/events/$id': typeof StaffEventsIdRoute
  '/staff/events/new': typeof StaffEventsNewRoute
  '/staff/reservierungen/$id': typeof StaffReservierungenIdRoute
  '/staff/events/': typeof StaffEventsIndexRoute
  '/staff/reservierungen/': typeof StaffReservierungenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/events'
    | '/impressum'
    | '/kontakt'
    | '/reservation'
    | '/restaurant'
    | '/speisekarte'
    | '/staff/analytics'
    | '/staff/dashboard'
    | '/staff/events'
    | '/staff/login'
    | '/staff/oeffnungszeiten'
    | '/staff/reservierungen'
    | '/staff/settings'
    | '/staff/sitzbereiche'
    | '/staff/team'
    | '/staff/events/$id'
    | '/staff/events/new'
    | '/staff/reservierungen/$id'
    | '/staff/events/'
    | '/staff/reservierungen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/events'
    | '/impressum'
    | '/kontakt'
    | '/reservation'
    | '/restaurant'
    | '/speisekarte'
    | '/staff/analytics'
    | '/staff/dashboard'
    | '/staff/login'
    | '/staff/oeffnungszeiten'
    | '/staff/settings'
    | '/staff/sitzbereiche'
    | '/staff/team'
    | '/staff/events/$id'
    | '/staff/events/new'
    | '/staff/reservierungen/$id'
    | '/staff/events'
    | '/staff/reservierungen'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/events'
    | '/impressum'
    | '/kontakt'
    | '/reservation'
    | '/restaurant'
    | '/speisekarte'
    | '/staff/analytics'
    | '/staff/dashboard'
    | '/staff/events'
    | '/staff/login'
    | '/staff/oeffnungszeiten'
    | '/staff/reservierungen'
    | '/staff/settings'
    | '/staff/sitzbereiche'
    | '/staff/team'
    | '/staff/events/$id'
    | '/staff/events/new'
    | '/staff/reservierungen/$id'
    | '/staff/events/'
    | '/staff/reservierungen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EventsRoute: typeof EventsRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  ReservationRoute: typeof ReservationRoute
  RestaurantRoute: typeof RestaurantRoute
  SpeisekarteRoute: typeof SpeisekarteRoute
  StaffAnalyticsRoute: typeof StaffAnalyticsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffEventsRoute: typeof StaffEventsRouteWithChildren
  StaffLoginRoute: typeof StaffLoginRoute
  StaffOeffnungszeitenRoute: typeof StaffOeffnungszeitenRoute
  StaffReservierungenRoute: typeof StaffReservierungenRouteWithChildren
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffSitzbereicheRoute: typeof StaffSitzbereicheRoute
  StaffTeamRoute: typeof StaffTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speisekarte': {
      id: '/speisekarte'
      path: '/speisekarte'
      fullPath: '/speisekarte'
      preLoaderRoute: typeof SpeisekarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/team': {
      id: '/staff/team'
      path: '/staff/team'
      fullPath: '/staff/team'
      preLoaderRoute: typeof StaffTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/sitzbereiche': {
      id: '/staff/sitzbereiche'
      path: '/staff/sitzbereiche'
      fullPath: '/staff/sitzbereiche'
      preLoaderRoute: typeof StaffSitzbereicheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/staff/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/reservierungen': {
      id: '/staff/reservierungen'
      path: '/staff/reservierungen'
      fullPath: '/staff/reservierungen'
      preLoaderRoute: typeof StaffReservierungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/oeffnungszeiten': {
      id: '/staff/oeffnungszeiten'
      path: '/staff/oeffnungszeiten'
      fullPath: '/staff/oeffnungszeiten'
      preLoaderRoute: typeof StaffOeffnungszeitenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/events': {
      id: '/staff/events'
      path: '/staff/events'
      fullPath: '/staff/events'
      preLoaderRoute: typeof StaffEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/analytics': {
      id: '/staff/analytics'
      path: '/staff/analytics'
      fullPath: '/staff/analytics'
      preLoaderRoute: typeof StaffAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/reservierungen/': {
      id: '/staff/reservierungen/'
      path: '/'
      fullPath: '/staff/reservierungen/'
      preLoaderRoute: typeof StaffReservierungenIndexRouteImport
      parentRoute: typeof StaffReservierungenRoute
    }
    '/staff/events/': {
      id: '/staff/events/'
      path: '/'
      fullPath: '/staff/events/'
      preLoaderRoute: typeof StaffEventsIndexRouteImport
      parentRoute: typeof StaffEventsRoute
    }
    '/staff/reservierungen/$id': {
      id: '/staff/reservierungen/$id'
      path: '/$id'
      fullPath: '/staff/reservierungen/$id'
      preLoaderRoute: typeof StaffReservierungenIdRouteImport
      parentRoute: typeof StaffReservierungenRoute
    }
    '/staff/events/new': {
      id: '/staff/events/new'
      path: '/new'
      fullPath: '/staff/events/new'
      preLoaderRoute: typeof StaffEventsNewRouteImport
      parentRoute: typeof StaffEventsRoute
    }
    '/staff/events/$id': {
      id: '/staff/events/$id'
      path: '/$id'
      fullPath: '/staff/events/$id'
      preLoaderRoute: typeof StaffEventsIdRouteImport
      parentRoute: typeof StaffEventsRoute
    }
  }
}

interface StaffEventsRouteChildren {
  StaffEventsIdRoute: typeof StaffEventsIdRoute
  StaffEventsNewRoute: typeof StaffEventsNewRoute
  StaffEventsIndexRoute: typeof StaffEventsIndexRoute
}

const StaffEventsRouteChildren: StaffEventsRouteChildren = {
  StaffEventsIdRoute: StaffEventsIdRoute,
  StaffEventsNewRoute: StaffEventsNewRoute,
  StaffEventsIndexRoute: StaffEventsIndexRoute,
}

const StaffEventsRouteWithChildren = StaffEventsRoute._addFileChildren(
  StaffEventsRouteChildren,
)

interface StaffReservierungenRouteChildren {
  StaffReservierungenIdRoute: typeof StaffReservierungenIdRoute
  StaffReservierungenIndexRoute: typeof StaffReservierungenIndexRoute
}

const StaffReservierungenRouteChildren: StaffReservierungenRouteChildren = {
  StaffReservierungenIdRoute: StaffReservierungenIdRoute,
  StaffReservierungenIndexRoute: StaffReservierungenIndexRoute,
}

const StaffReservierungenRouteWithChildren =
  StaffReservierungenRoute._addFileChildren(StaffReservierungenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  EventsRoute: EventsRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  ReservationRoute: ReservationRoute,
  RestaurantRoute: RestaurantRoute,
  SpeisekarteRoute: SpeisekarteRoute,
  StaffAnalyticsRoute: StaffAnalyticsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffEventsRoute: StaffEventsRouteWithChildren,
  StaffLoginRoute: StaffLoginRoute,
  StaffOeffnungszeitenRoute: StaffOeffnungszeitenRoute,
  StaffReservierungenRoute: StaffReservierungenRouteWithChildren,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffSitzbereicheRoute: StaffSitzbereicheRoute,
  StaffTeamRoute: StaffTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
